version: "3.3"

services:
  backend:
    build: .
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    container_name: backend_app
    ports:
      - 3001:3001
    stdin_open: true

# docker-compose up -d
